- name: "Include de Ansible-Vault file."
  include_vars:
    file: ../../../group_vars/WindowsServer/vault.yml
  no_log: true

- name: Installeer de volgende rollen.
  ansible.windows.win_feature:
    name: "{{ item }}"
    state: present
    include_sub_features: true
    include_management_tools: true
  loop:
    - AD-Domain-Services
    - DHCP
    - DNS
    - WDS