- hosts: LinuxServer
  gather_facts: true
  become: true
  roles:
  - { role: docker, tags: [ 'docker']}
  - { role: linux, tags: [ 'linux']}
  - { role: linux_users, tags:  [ 'linux_users']}
  - { role: ntp, tags: [  'ntp']}

- hosts: routers 
  gather_facts: true
  become: true
  roles:
  - { role: routers, tags: [ 'routers']}

- hosts: switches
  gather_facts: true
  become: true
  roles:
  - { role: switches, tags: [ 'switches']}

- hosts: WindowsServer
  gather_facts: true
  become: yes
  become_method: runas
  become_user: Administrator
  roles:
  - { role: windows, tags: [ 'windows']}
  - { role: windows_adds, tags: [ 'adds']}
  - { role: windows_agdlp, tags: [ 'agdlp']}
  - { role: windows_backup, tags: [ 'backup']}
  - { role: windows_dhcp, tags: [ 'dhcp']}
  - { role: windows_dns,  tags: [ 'dns']}
  - { role: windows_firewall, tags: [ 'firewall']}
  - { role: windows_gpo,  tags: [ 'gpo']}
  - { role: windows_ou, tags: [ 'ou']}
  - { role: windows_restore, tags: [ 'restore']}
  - { role: windows_shares, tags: [ 'shares']}
  - { role: windows_ssh, tags: [ 'ssh']}
  - { role: windows_users, tags: [ 'users']}
  - { role: windows_updates, tags: [ 'updates']}

- hosts: Werkstations
  gather_facts: true
  become: yes
  become_method: runas
  become_user: michel
  roles:
  - { role: werkstations, tags: [ 'werkstations']}
  - { role: windows_apps, tags: [ 'apps']}
  - { role: windows_ai_nvidia, tags: [ 'nvidia']}
  - { role: windows_ai_amd, tags: [ 'amd']}