- name: Clone de Git-repo met de commandline (AMD VERSION)
  ansible.windows.win_shell: |
    git clone https://github.com/lshqqytiger/stable-diffusion-webui-directml C:\AI\stable-diffusion-webui
    cd C:\AI\stable-diffusion-webui
    git submodule init
    git submodule update
  args:
    executable: cmd

# - name: Reboot het werkstation
#   ansible.windows.win_reboot:

- name: Genereer Jinja2-template voor webui-user.bat
  ansible.builtin.template:
    src: roles/windows_ai/tasks/webui-user.bat.j2
    dest: C:\AI\stable-diffusion-webui\webui-user.bat

- name: Voer webui-user.bat uit
  args:
    executable: cmd
    chdir:  C:\AI\stable-diffusion-webui
  script: 'C:\AI\stable-diffusion-webui\webui-user.bat'
