ansible_host: 192.168.16.183

# ADDS
dns_domain_name: "noorderpoort.intern"
domain_netbios_name: "NOORDERPOORT"
check_netbios_name: "NOORDERPOORT\\Michel"
domain_admin_user: "Administrator@noorderpoort.intern"

domain: "noorderpoort"
controller: "intern"

#DHCP

FQDN: WS2019.noorderpoort.intern
DHCP_SCOPE_NAME: "TestScope"
start_range: 192.168.16.150
end_range: 192.168.16.175
subnetmask: 255.255.255.0
dnsserver: "{{ansible_host}}"
router: 192.168.16.1
scopeid: "192.168.16.0/24"

#OU
rootOU: "NPAfdelingen"