# Maakt de map AI aan

- name: Controleer of de map C:\AI bestaat
  win_stat:
    path: C:\AI
  register: temp_dir_info
  ignore_errors: true

- name: Maak de map C:\AI aan als deze niet bestaat
  win_file:
    path: C:\AI
    state: directory
  when: not temp_dir_info.stat.exists


# Installeer python

- name: Download Python-installatieprogramma
  win_get_url:
    url: https://www.python.org/ftp/python/3.10.6/python-3.10.6-amd64.exe
    dest: C:\AI\python-3.10.6-amd64.exe

- name: Installeer Python
  win_command: C:\AI\python-3.10.6-amd64.exe /quiet
  register: install_result



# Installeer Git op windows

- name: Download Git-installatieprogramma
  win_get_url:
    url: https://github.com/git-for-windows/git/releases/download/v2.42.0.windows.2/Git-2.42.0.2-64-bit.exe
    dest: C:\AI\Git-2.42.0.2-64-bit.exe

- name: Installeer Git
  win_command: C:\AI\Git-2.42.0.2-64-bit.exe /VERYSILENT /NORESTART /COMPONENTS="icons,ext\reg\shellhere,assoc,assoc_sh"

- name: Controleer Git-versie
  win_command: git --version
  register: git_version

- name: Debug - Controleren van Git-versie
  debug:
    var: git_version.stdout


# Installeer de juiste github repo

- name: Clone de Git-repo met de commandline
  win_shell: |
    git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git C:\AI\stable-diffusion-webui
  args:
    executable: cmd

# reboot het werkstation

- name: Reboot het werkstation
  ansible.windows.win_reboot:


# voer het .bat bestand uit:

- name: Voer webui-user.bat uit
  script: 'C:\AI\stable-diffusion-webui\webui-user.bat'
  args:
    executable: cmd
